workflows:
  unity-win64-workflow:
      name: Unity Win64 Workflow
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        vars:
          UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
          BUILD_SCRIPT: BuildWin64
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Activate License
          script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
        - name: Build
          script: $UNITY_BIN -batchmode -quit -logFile -projectPath ./uConsole -executeMethod BuildScript.$BUILD_SCRIPT -nographics
      publishing:
        scripts:
          - name: Deactivate License
            script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
